HscDir = ".testnet"

[GenesisDoc]
GenesisTime = 2021-03-18T09:32:42Z
ChainName = "HSC"
ChainID = "666"
[GenesisDoc.Params]
ProposalThreshold = 1
[GenesisDoc.GlobalPermissions]
[GenesisDoc.GlobalPermissions.Base]
Perms = "send | call | createContract | createAccount | bond | name | proposal | input | batch | hasBase | hasRole"
SetBit = "root | send | call | createContract | createAccount | bond | name | proposal | input | batch | identify | hasBase | setBase | unsetBase | setGlobal | hasRole | addRole | removeRole"

[[GenesisDoc.Accounts]]
Address = "0EAFE809AA10D24E31E362C20BED09C884BDE336"
Amount = 0
Power = 99999
Pegged = 0
Name = "Validator_0"
PublicKey = "{\"CurveType\":\"ed25519\",\"PublicKey\":\"B80035E1E4F5DE9CE54D84CBF8B9F42F9B2F4FD0256C0A5646474ABCDAD46E61\"}"
[GenesisDoc.Accounts.Permissions]
[GenesisDoc.Accounts.Permissions.Base]
Perms = "send | call | name | proposal | input | hasRole | bond"
SetBit = "send | call | name | proposal | input | hasRole | bond"

[[GenesisDoc.Accounts]]
Address = "A8F452BDE08747AEAF29723CD94618EC0FC8C91D"
Amount = 0
Power = 99999
Pegged = 0
Name = "Validator_1"
PublicKey = "{\"CurveType\":\"ed25519\",\"PublicKey\":\"5E3A36537D89FFED5F435708F43C7F48030327FA834D00735F87646C834B06DD\"}"
[GenesisDoc.Accounts.Permissions]
[GenesisDoc.Accounts.Permissions.Base]
Perms = "send | call | name | proposal | input | hasRole | bond"
SetBit = "send | call | name | proposal | input | hasRole | bond"

[[GenesisDoc.Accounts]]
Address = "D0243FEF063E1CEB950673E593020B9ADA7C84B1"
Amount = 0
Power = 99999
Pegged = 0
Name = "Root_0"
PublicKey = "{\"CurveType\":\"ed25519\",\"PublicKey\":\"82E6DE6829F68D16FB15478B81CA5911E63CF3FDD254E51F748CD3F021EF7896\"}"
[GenesisDoc.Accounts.Permissions]
[GenesisDoc.Accounts.Permissions.Base]
Perms = "root | send | call | createContract | createAccount | bond | name | proposal | input | batch | identify | hasBase | setBase | unsetBase | setGlobal | hasRole | addRole | removeRole"
SetBit = "root | send | call | createContract | createAccount | bond | name | proposal | input | batch | identify | hasBase | setBase | unsetBase | setGlobal | hasRole | addRole | removeRole"

[[GenesisDoc.Accounts]]
Address = "6DFBB2FD32E828C53FD0C0B1359EC121460FABA6"
Amount = 0
Power = 0
Pegged = 0
Name = "Participant_0"
PublicKey = "{\"CurveType\":\"ed25519\",\"PublicKey\":\"FAF15DA263B6ECE7A6109BB2CCE3014F28A5369010C74BA4BBA0A0D1D4BF26F8\"}"
[GenesisDoc.Accounts.Permissions]
[GenesisDoc.Accounts.Permissions.Base]
Perms = "send | call | name | proposal | input | hasRole"
SetBit = "send | call | name | proposal | input | hasRole"

[[GenesisDoc.Accounts]]
Address = "17E393AEBDDF15884530906815321F73C7F2DC5D"
Amount = 0
Power = 0
Pegged = 0
Name = "Participant_1"
PublicKey = "{\"CurveType\":\"ed25519\",\"PublicKey\":\"5CE6B7A7C45E8870060453EBCED9C5743D040275C896AF372AC36FC17C601054\"}"
[GenesisDoc.Accounts.Permissions]
[GenesisDoc.Accounts.Permissions.Base]
Perms = "send | call | name | proposal | input | hasRole"
SetBit = "send | call | name | proposal | input | hasRole"

[[GenesisDoc.Accounts]]
Address = "D4B5286A2C70DFE8501FDAA17B56A542F43FF6ED"
Amount = 0
Power = 0
Pegged = 0
Name = "Participant_2"
PublicKey = "{\"CurveType\":\"ed25519\",\"PublicKey\":\"EE0E82A8802A1399294CFD12F7C59CDCEF51213335E5BFD0BA95FD686DF8D73F\"}"
[GenesisDoc.Accounts.Permissions]
[GenesisDoc.Accounts.Permissions.Base]
Perms = "send | call | name | proposal | input | hasRole"
SetBit = "send | call | name | proposal | input | hasRole"

[[GenesisDoc.Validators]]
Address = "0EAFE809AA10D24E31E362C20BED09C884BDE336"
Amount = 0
Power = 0
Pegged = 0
Name = "Validator_0"
PublicKey = "{\"CurveType\":\"ed25519\",\"PublicKey\":\"B80035E1E4F5DE9CE54D84CBF8B9F42F9B2F4FD0256C0A5646474ABCDAD46E61\"}"

[[GenesisDoc.Validators.UnbondTo]]
Address = "0EAFE809AA10D24E31E362C20BED09C884BDE336"
Amount = 0
Power = 0
Pegged = 0
PublicKey = "{\"CurveType\":\"ed25519\",\"PublicKey\":\"B80035E1E4F5DE9CE54D84CBF8B9F42F9B2F4FD0256C0A5646474ABCDAD46E61\"}"

[[GenesisDoc.Validators]]
Address = "A8F452BDE08747AEAF29723CD94618EC0FC8C91D"
Amount = 0
Power = 0
Pegged = 0
Name = "Validator_1"
PublicKey = "{\"CurveType\":\"ed25519\",\"PublicKey\":\"5E3A36537D89FFED5F435708F43C7F48030327FA834D00735F87646C834B06DD\"}"

[[GenesisDoc.Validators.UnbondTo]]
Address = "A8F452BDE08747AEAF29723CD94618EC0FC8C91D"
Amount = 0
Power = 0
Pegged = 0
PublicKey = "{\"CurveType\":\"ed25519\",\"PublicKey\":\"5E3A36537D89FFED5F435708F43C7F48030327FA834D00735F87646C834B06DD\"}"

[Tendermint]
Enabled = true
Seeds = ""
SeedMode = false
PersistentPeers = "206.45.142.209:26656, 185.130.44.165:26656"
ListenHost = "0.0.0.0"
ListenPort = "26656"
ExternalAddress = "185.130.44.72:26656"
AddrBookStrict = false
Moniker =  "SeedServer"
IdentifyPeers = true
AuthorizedPeers = ""
CreateEmptyBlocks = "3s"
MaxNumPeers = 50

[Execution]
TimeoutFactor = 0.1
CallStackMaxDepth = 0
DataStackInitialCapacity = 1024
DataStackMaxDepth = 0

[Keys]
GRPCServiceEnabled = false
AllowBadFilePermissions = true
RemoteAddress = ""
KeysDirectory = ".keys"

[RPC]
[RPC.Info]
Enabled = true
ListenHost = "0.0.0.0"
ListenPort = "26658"
[RPC.Profiler]
Enabled = true
ListenHost = "0.0.0.0"
ListenPort = "6060"
[RPC.GRPC]
Enabled = true
ListenHost = "0.0.0.0"
ListenPort = "10997"
[RPC.Metrics]
Enabled = true
ListenHost = "0.0.0.0"
ListenPort = "9102"
MetricsPath = "/metrics"
BlockSampleSize = 100
[RPC.Web3]
Enabled = true
ListenHost = "0.0.0.0"
ListenPort = "26660"

[Logging]
Trace = false
NonBlocking = false
[Logging.RootSink]
[Logging.RootSink.Output]
OutputType = "stdout"
Format = "json"
